remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#theme: minimal-mistakes-jekyll
plugins:
        - jekyll-remote-theme # add this line to the plugins list if you already have one
        - jekyll-include-cache

minimal_mistakes_skin: "air" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
title: "RNABSdb"
subtitle: "RNA Binding Sites database"
name: "MolinerisLab"
repository: "molinerisLab/RNABSdb"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-SRKQ908YDT"
    anonymize_ip: false # default

breadcrumbs: true  # disabled by default
atom_feed:
  hide: true

search: true

include: ["_pages"]


after_footer_scripts:
#  - https://code.jquery.com/jquery-3.3.1.min.js
   - https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js
   - https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js
   - https://cdn.datatables.net/buttons/2.2.3/js/buttons.colVis.min.js
   - /assets/js/load_datatable.js
